// Example 50 questions
QUESTIONS = [
    {q:"Which document is known as the foundation of modern human rights?", choices:["Universal Declaration of Human Rights","Magna Carta","US Constitution","Napoleonic Code"], a:0},
    {q:"What year was the Universal Declaration of Human Rights adopted by the UN?", choices:["1948","1939","1960","1955"], a:0},
    {q:"Freedom of speech is an example of which type of right?", choices:["Civil and political rights","Economic rights","Cultural rights","Environmental rights"], a:0},
    {q:"Which right protects a person's body from torture?", choices:["Right to life","Right to liberty","Freedom from torture","Right to property"], a:2},
    {q:"The right to education is mainly classified under:", choices:["Economic, social and cultural rights","Civil rights","Political rights","Collective rights"], a:0},
    {q:"Which of these is a protected ground under many anti-discrimination laws?", choices:["Race","Favorite color","Height","Shoe size"], a:0},
    {q:"What does 'due process' ensure?", choices:["Fair legal procedures","Free healthcare","Free housing","Unlimited speech"], a:0},
    {q:"Children have special protection under human rights law because:", choices:["They are vulnerable and need care","They can vote","They pay taxes","They are always guilty"], a:0},
    {q:"Which right allows people to choose their leaders?", choices:["Right to vote","Right to work","Freedom of movement","Right to privacy"], a:0},
    {q:"What does 'international humanitarian law' mainly regulate?", choices:["Conduct during armed conflict","Tax policy","Trade agreements","Healthcare delivery"], a:0},
    {q:"Which body monitors human rights globally?", choices:["United Nations Human Rights Council","Local police","World Bank","OECD"], a:0},
    {q:"Freedom of religion includes:", choices:["Choosing and changing one's religion","Mandatory state religion","Prohibiting all religions","Only private practice"], a:0},
    {q:"What is forced labour?", choices:["Work performed under threat or coercion","Voluntary charity work","Internships","Hobby"], a:0},
    {q:"Which right concerns keeping personal information private?", choices:["Right to privacy","Right to housing","Right to vote","Right to education"], a:0},
    {q:"The right to asylum is related to:", choices:["Protection for refugees","Tax avoidance","Trade benefits","Passport control"], a:0},
    {q:"Which practice violates human rights?", choices:["Arbitrary detention","Public libraries","Community gardening","Voting"], a:0},
    {q:"Which right ensures people can form associations?", choices:["Freedom of assembly","Right to bear arms","Right to strike only","No rights"], a:0},
    {q:"Equality before the law means:", choices:["Everyone treated fairly by courts","Only citizens get rights","Only the rich get protection","Laws only for adults"], a:0},
    {q:"What is discrimination?", choices:["Unfair treatment based on group characteristics","Treating everyone the same","Offering discounts","Hiring more people"], a:0},
    {q:"Access to clean water is linked to which right?", choices:["Right to an adequate standard of living","Right to expression","Right to a fair trial","Right to vote"], a:0},
    {q:"Which right protects people from being killed unlawfully?", choices:["Right to life","Freedom of movement","Right to work","Right to education"], a:0},
    {q:"Which international court tries genocide and war crimes?", choices:["International Criminal Court","International Court of Trade","World Health Court","Bankruptcy Court"], a:0},
    {q:"What does 'non-discrimination' require states to do?", choices:["Treat people equally regardless of protected status","Prefer some groups","Ignore complaints","Sell public land"], a:0},
    {q:"Gender equality in human rights means:", choices:["Same rights and opportunities for all genders","Only women have rights","Only men have rights","Gender must be ignored entirely"], a:0},
    {q:"What does 'safe and legal migration' promote?", choices:["Human rights protection for migrants","Complete border closures","No migration at all","Forced return"], a:0},
    {q:"Which right supports a fair wage and safe working conditions?", choices:["Right to work and favourable conditions","Right to privacy","Right to assembly","Right to bear arms"], a:0},
    {q:"When speech incites violence, it may be:", choices:["Restricted under law","Always allowed","Rewarded","Ignored"], a:0},
    {q:"Which group needs protection from age discrimination?", choices:["Older people and children","Only adults","Only teenagers","Only newborns"], a:0},
    {q:"What is civic space?", choices:["The environment where people organize and express views","A public park","Online gaming servers","A courtroom"], a:0},
    {q:"Which right allows access to information held by public bodies?", choices:["Right to information","Right to private property","Right to censorship","Right to indefinite detention"], a:0},
    {q:"What does 'stigma' do to people with health conditions?", choices:["Harms their social acceptance","Ensures fair treatment","Improves care","Has no effect"], a:0},
    {q:"Which principle requires accountability for human rights violations?", choices:["Rule of law","Absolute immunity","Secrecy","Randomness"], a:0},
    {q:"Which right helps people keep families together?", choices:["Right to family life","Right to property only","Right to assembly only","Right to strike only"], a:0},
    {q:"The right to a fair trial includes:", choices:["Impartial judge and chance to present a defence","Automatic guilt","No legal representation","Secret courts only"], a:0},
    {q:"Which is an economic right?", choices:["Right to social security","Right to vote","Freedom of religion","Freedom of expression"], a:0},
    {q:"What is cultural rights protection about?", choices:["Allowing groups to practise their culture","Forbidding cultural expression","Only national culture matters","Cultural privatization"], a:0},
    {q:"Why are human rights universal?", choices:["They apply to everyone, everywhere","Only apply to some countries","Only to adults","Only when convenient"], a:0},
    {q:"What duty do states have under human rights law?", choices:["Respect, protect and fulfil rights","Ignore rights","Abolish rights","Privatize rights"], a:0},
    {q:"Which tool helps protect rights in emergencies?", choices:["Human rights monitoring and safeguards","Censorship","Arbitrary rule","Tunnel networks"], a:0},
    {q:"Which action strengthens human rights education?", choices:["Teaching rights in schools","Removing civics classes","Banning discussion","Only training police"], a:0},
    {q:"What is a non-state actor?", choices:["An entity not part of government (company, group)","A judge","A mayor","A law"], a:0},
    {q:"Which right relates to participation in cultural life?", choices:["Right to participate in cultural life","Right to silence only","Right to solitude only","Right to censorship"], a:0},
    {q:"What does reparations mean?", choices:["Compensation/relief for victims","Punishment only","Expulsion","Privacy invasion"], a:0},
    {q:"Which mechanism lets citizens complain about rights violations?", choices:["National human rights institutions and courts","Only the police","Only social media","No mechanism"], a:0},
    {q:"What is xenophobia?", choices:["Fear or hatred of foreigners","A cultural festival","A charity program","A legal right"], a:0},
    {q:"Why is independent media important?", choices:["It holds power to account and informs citizens","It spreads propaganda only","It censors critics","It replaces courts"], a:0},
    {q:"What role does civil society play?", choices:["Advocacy, support and watchdog functions","Runs all courts","Is the government","Repeats laws"], a:0},
    {q:"Which practice is child labour?", choices:["Children doing dangerous paid work","After-school homework","Voluntary clubs","Reading books"], a:0},
    {q:"What is an extrajudicial killing?", choices:["Killing without legal process","A lawful death penalty","An accident only","A medical procedure"], a:0},
    {q:"What can privacy protections help prevent?", choices:["Surveillance abuse and identity theft","Voting rights","Right to education","Freedom of religion"], a:0},
    {q:"Which right helps protect people during detention?", choices:["Right against torture and ill-treatment","Right to unlimited detention","Right to indefinite solitude","No rights"], a:0},
    {q:"What is a peaceful protest's main requirement?", choices:["Not to use violence","To block all roads","To be secret","To be violent"], a:0},
    {q:"Which right allows fair pay and safe workplaces?", choices:["Labour rights and protections","Right to censorship","Right to exile","Absolute property rights"], a:0},
    {q:"What is the aim of human rights defenders?", choices:["Protect human rights and support victims","To break laws","To seize power","To censor communities"], a:0}    // ... add more until 50
];
